### ISSUE TITLE
Scrape sexyVR scenes from povr.com

### ISSUE THREAD

**Issue by str0keR** [xbapps/xbvr#1042]
Please can someone add support for scraping sexyvr scenes from somewhere like [pr](https://povr.com/sexyvr/)

**Comment by toshski** [comment]
Try scrapping Bravo Models

This looks like the same Studio as Bravo Models which is already scraped from SLR.  It does look like it's had any new scenes on POVR since late 2020, SLR has scenes as recent as March 2022.  Vrporn also has them but it's last scene was April 2022, so I suspect they have stop publishing content.

**Comment by theRealKLH** [comment]
@str0keR Cleaning up "dead" issues. if still an issue, reopen with more information.
