### ISSUE TITLE
Videos with MP4V codecs doesn't play

### ISSUE THREAD

**Issue by henkyprayoga** [xbapps/xbvr#1051]
I'm having difficulties on playing videos encoded in MP4 both in browser and also DeoVR. Here's the codec information when its played on VLC. VLC play the video just fine.

<img width="301" alt="Screenshot 2022-12-05 231728" src="https://user-images.githubusercontent.com/862744/205687243-ec0716a0-c36e-4781-bd61-8f70d05b625b.png">

**Comment by vt-idiot** [comment]
1. mp4v wouldn't normally be used as a "codec" - unless it actually means [MP4V-ES](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#mp4v-es)/MPEG-4 Part 2...that means H.263. If you're old enough to remember it, it basically means it's the same underlying technology as **XviD or DivX.**
2. The issue here isn't XBVR, or DeoVR, or Heresphere, or or or. VLC can play it back because it's decoding it using your CPU. I reckon if you tried to watch it using Whirligig it _might_ play back with the VLC playback option enabled. That codec was never ever meant for 5408x2720, and hardly worked well for 720p. I'm not even sure how StasyQVR encoded such a ridiculous file. 
3. `GUSH(rarbg)\` - try to be less obvious ;) - whoever made that release should feel even dumber than the tools releasing >4096x2048 AVC/H.264 videos when HEVC versions exist at the source as well...

Checking the source, SLR in this case, you can see that the file they state is the "original" does in fact say 5400x2700 mpeg-4 right next to it. And nobody from StasyQ all the way to SLR ever thought it was a problem:
![image](https://user-images.githubusercontent.com/81622808/209387865-8e3c6dcc-fe85-4bd2-8640-1d712084e863.png)

Solution: Pay for the video and download it in a proper codec.
Alternatively: Download ffmpeg, some kind of GUI front-end for ffmpeg, Handbrake, etc - and transcode the video to HEVC using x265. It probably looks like garbage already, so you'd save time and electricity by allowing your GPU to encode it instead - be it through AMD VCE/VCN on a Radeon card, which will probably also require you to resize it to 3840x1920 unless it's a very new card, or using CUVID or whatever nVIDIA calls it these days.

PS. It took 1 minute to find the 2.25 GB H.265 version. It's out there.

**Comment by Rakly3** [comment]
> And nobody from StasyQ all the way to SLR ever thought it was a problem:

SLR representative here.

We post the unaltered original studio files as they are uploaded to us. - There is no guarantee of compatibility here.
The transcodes are done by SLR and guaranteed to be compatible in the SLR app.

**Comment by Rakly3** [comment]
> I'm having difficulties on playing videos encoded in MP4 both in browser and also DeoVR. Here's the codec information when its played on VLC. VLC play the video just fine.
> 
> <img alt="Screenshot 2022-12-05 231728" width="301" src="https://user-images.githubusercontent.com/862744/205687243-ec0716a0-c36e-4781-bd61-8f70d05b625b.png">

Just some FYI.
As @vt-idiot already alluded to, 'MP4' isn't a codec. People use the term codec for all kinds of things, and usually the wrong ones.

You can view MP4 as a big box. This box has all kinds of shaped holes in it, Square hole, egg-shaped hole, star-shape hole, etc.
You can put into that box anything you want, as long it matches one of the shapes of the holes.

A more concrete example. MP4 can not play spatial audio, it doesn't have a 'hole' for it. While MKV on the other hand, does!
Yet, both the mp4 and mkv boxes can hold the identical video because they both have the shape as a hole.
The video will play for both, but you won't have audio from the mp4 'box.'


I have a very easy to follow video guide to get around this kind of problem, without re-encoding the video and free (professional grade) software. If you're interested.
https://drive.google.com/file/d/1kYAs_tLPHNu9BV9rVqYLbBS-SowoK0pY/view?usp=share_link

**Comment by theRealKLH** [comment]
@henkyprayoga cleaning up "dead" issues. Your problem is not related to xbvr.

**Comment by Rakly3** [comment]
> And nobody from StasyQ all the way to SLR ever thought it was a problem:

That's not true, those are the files the studio send to us. We did not encode that specific file.
