### ISSUE TITLE
unable to generate preview

### ISSUE THREAD

**Issue by threesquare** [xbapps/xbvr#1115]
was able to do so a while ago. getting this error below now
`time="2023-02-03T01:32:34Z" level=info msg="Generating previews"
time="2023-02-03T01:32:34Z" level=info msg="Rendering naughtyamerica-vr-31582"
time="2023-02-03T01:32:34Z" level=warning msg="signal: bus error"`

**Comment by theRealKLH** [comment]
most likely something wrong with that video. to test you could relocate the video and start generating previews again. if no errors, then you know it's definitely a "bad" video.

**Comment by threesquare** [comment]
> most likely something wrong with that video. to test you could relocate the video and start generating previews again. if no errors, then you know it's definitely a "bad" video.

it's happening to all new videos added. The videos are properly located too, I'm able to play it via the app. The test function in the generating video fail to test render as well.

**Comment by theRealKLH** [comment]
I don't think this is an xbvr issue (however if it stopped after installing new release, try reverting to previous version). More a problem w/ffmpeg... xbvr isn't generating the previews. Which xbvr (win,mac,linux,docker)? Have you tried restarting your computer?

**Comment by threesquare** [comment]
> I don't think this is an xbvr issue (however if it stopped after installing new release, try reverting to previous version). More a problem w/ffmpeg... xbvr isn't generating the previews. Which xbvr (win,mac,linux,docker)? Have you tried restarting your computer?

I'm running it as a docker in my NAS using Unraid. I've restarted the NAS plenty of time since this issue popup. I can't recall which version of XBVR when it was last generating the preview. I would hate to reinstall XBVR and lose my database.

**Comment by theRealKLH** [comment]
If you are running docker.. HOPEFULLY you mounted a directory on your NAS to hold config (folder inside container /.root/config).  I don't know how that is done in unraid. That's the only way not to lose your data (not just db, but previews, image cache, etc). You can always copy the xbvr.db file OR do an export prior to deleting/rebuilding the container. What you could try is shut down xbvr, go into the config dir and delete the ffmpeg files. next time you launch it should re-download them. Maybe somehow you have a corrupt ffmpeg. OR it's some hardware error (memory). 

I'm just throwing some basic suggestions out there because I don't know what could be causing the issue. google points to "bus error" as trying to access invalid memory location (doesn't exist).

**Comment by threesquare** [comment]
> What you could try is shut down xbvr, go into the config dir and delete the ffmpeg files. next time you launch it should re-download them. Maybe somehow you have a corrupt ffmpeg.

that fixed it! thank you, appreciate the help.

**Comment by RonnieBlaze** [comment]
> > What you could try is shut down xbvr, go into the config dir and delete the ffmpeg files. next time you launch it should re-download them. Maybe somehow you have a corrupt ffmpeg.
> 
> that fixed it! thank you, appreciate the help.

mind sharing your docker setup for unraid? i am trying to get it working on my unraid server as well.
