### ISSUE TITLE
Add to favorite button doesn't work on video info page

### ISSUE THREAD

**Issue by Thatkookooguy** [xbapps/xbvr#1116]
1. go into the info of  a specific video
2. try clicking the add to favorite button
3. nothing happens

---
I can add to favorite from the grid view, but not from the video info

**Comment by toshski** [comment]
I have noticed if I use the search (quick find) and go into the scene detail and click favorite, or even some of the other buttons, it's appearance does not toggle.  But it does actually, change the value, you should see that when you exit to the grid (unless you pressed it twice).  If I click on a scene in the grid view to go the scene details, changing then works fine.  Haven't been able to work out why how you go into the Scene Detail should make a difference.

**Comment by crwxaj** [comment]
The problem lies here: https://github.com/xbapps/xbvr/blob/413aec6641b439aa02efd72d4bf07550339a56f8/ui/src/store/sceneList.js#L86
The toggle gets executed in the sceneList, which also toggles the scene details view, if the scene comes from the scene list. This isn't the case when the scene details were opened from the Quick Find drop down. I gave it a shot, but struggled with the Vue data model. Maybe someone else can have a look.
