### ISSUE TITLE
Playback from Heresphere doesn't work if there is a percent in the scene title

### ISSUE THREAD

**Issue by Alderamin49ly** [xbapps/xbvr#1220]
The URL in the media sources in the Heresphere API is generated with the scene title. If the scene title contains a % symbol, it is not escaped, thus causing an invalid URL that returns a "400 Bad Request" response when called.

This happens with XBVR 0.4.6.

**Comment by vt-idiot** [comment]
It's been a while since I dealt with this, but it's because "URL percent encoding" ends up screwing things up. ie. with "100% Success" in the title, you'd end up with Heresphere trying to interpret a URL percent encoded `% ` or `%%20` - neither of which would be valid. While there might be a way to have XBVR properly escape the titles on the API side, or even remove them during scraping as a nuclear option so that this doesn't happen, it's far easier to just remove the percent sign, or write it out as "percent".
I only had it on a handful of JAV scenes, and since those don't scrape automatically, I manually edited them all in main.db. If you have scenes that came from an actual site scraper with % in the title, edit them directly in the UI so that they're logged as "edits" and not restored the next time you scrape.

**Comment by theRealKLH** [comment]
wouldn't this be a HereSphere issue, not XBVR? we are sending a JSON file correct? HereSphere needs to know how to handle the data in the JSON. title = "100% success". HereSphere didn't say we have to encode anything in the fields in the JSON (I don't think). I'm asking without taking a look at any code (plus the fact that where I am at the moment would be a nono because of content-grin).

**Comment by vt-idiot** [comment]
and so I don't get TMI'd twice in one day

@theRealKLH TL;DR it's because `%!` isn't a valid percent string in a URL (in my example) // because Chromium doesn't want to automatically encode `%` to `%25` // because XBVR is expecting `%25` when it should also honor a request for `%`

take your pick

**Comment by vt-idiot** [comment]
and now that I think about it, the combination of the way XBVR is serving up the JSON **and** it returning 400 for the request is _technically_ what's wrong...% is "reserved" in RFC 3986. it _should_ be encoded https://en.wikipedia.org/wiki/URL_encoding#Reserved_characters

technically a lot of other characters in titles _should_ be encoded, like `:` but...even though a browser won't automatically encode it when it encounters it in your address bar (or you try to request it, whatever) - XBVR does **not** return HTTP 400 when you try to visit a scene with `:` in the title, ie. unencoded `From The Vault: ` in any number of VRHush scenes: `...8333%20-%20From%20the%20Vault꞉%20Abella%20Undresses%...` plus it loads anyways if you DO percent encode `:` as `%3A` - a la `...file/6338/8333%20-%20From%20the%20Vault%3A%20Abella%20Undresses%20To...`

it does seem to be unique to the % symbol

**Comment by theRealKLH** [comment]
> and so I don't get TMI'd twice in one day
> 
HAH! That was because you answered for somebody else. GRIN

Now that you sent over that JSON I see what you mean. I was about to respond "Why would we encode anything in title. It has nothing to do with URL". I haven't looked at things in a very long time. I didn't realize everything was changed from `http://1.2.3.4:9999/api/dms/file/3761/13353` to `http://1.2.3.4:9999/api/dms/file/3761/13353 - whatever the title might be`. (it might have always been that way). I need to validate that when I get home.
