### ISSUE TITLE
POVR URLs changed, all POVR filenames now missing their site prefix

### ISSUE THREAD

**Issue by vt-idiot** [xbapps/xbvr#1249]
POVR URLs seem to have changed? What used to be `https://povr.com/povr-originals/less-is-moore-6328021` is now `https://povr.com/vr-porn/less-is-moore-6328021` and it seems to apply to all of them - or at least to wankz, POVR, and BrasilVR. That changed all filenames in my database for all of their scenes, said scene now wants to match to `vr-porn-less-is-moore-180_180x180_3dh_LR.mp4` instead of `povr-originals-less-is-moore-180_180x180_3dh_LR.mp4` like it used to.

[povr.go](https://github.com/xbapps/xbvr/blob/d3f428ca070b0921c0ec4277fdcd09479bf687a0/pkg/scrape/povr.go#L55)
```go
		// Filenames
		studioBase := path.Base(strings.TrimSuffix(siteURL, "/"))
		sceneBase := path.Base(strings.TrimSuffix(e.Request.URL.Path, "/"))
		sceneBase = strings.Split(sceneBase, sc.SiteID)[0]

		base := studioBase + "-" + sceneBase
		sc.Filenames = append(sc.Filenames, base+"180_180x180_3dh_LR.mp4")
```

> `		studioBase := path.Base(strings.TrimSuffix(siteURL, "/"))`
That just grabs `vr-porn` for everything scraped from POVR now.

might be an easy fix? could studioBase be re-done to look for a `<a href="/studios/` and take whatever is between that and the following `"` (with whatever the appropriate div/class/span/whatever selector is to avoid grabbing something from the sidebar) because I think that might work for all of them

![image](https://user-images.githubusercontent.com/81622808/233843482-6484e776-728e-4cfc-9c15-2e9f6fbfc227.png)

**Comment by theRealKLH** [comment]
looks fine on my side.. 
![image](https://user-images.githubusercontent.com/65736720/233859254-6eea263f-1d27-45bf-9715-1bcb7c47e290.png)
![image](https://user-images.githubusercontent.com/65736720/233859642-9b68f938-78e0-4bb8-b215-9358d1069835.png)


Are you running 0.4.6? PR #1210 is the only POVR filename fix that I see recently. Maybe you got caught between POVR making changes? I know that recently filenames were being generated with `vr-porn-` instead of say `milfvr-`. Maybe you just need a forced update to fix your existing scenes?

**Comment by vt-idiot** [comment]
I am indeed on 0.4.6

I was ready to say, "I think the opposite happened, you caught the scraper switch _before_ they changed their URLs? Because URLs like `https://povr.com/povr-originals/less-is-moore-6328021` - which would've given me the "right" filenames, are redirecting me to `https://povr.com/vr-porn/less-is-moore-6328021` - giving me the "wrong" filenames." But I just forced an update on one scene and it did indeed fix the filenames...weird. Thank you.
