### ISSUE TITLE
Move 'assign file this scene' from dropdown to inline

### ISSUE THREAD

**Issue by dan9qt** [xbapps/xbvr#134]

**Comment by cld9x** [comment]
That’s reasonable thing to do, can’t tell what I had on mind while putting that button inline

**Comment by vpfruitly** [comment]
Yes, please! I adjust filenames after download, so I have to manually match everything.

Something else that would make the manual scene assignment workflow much faster is a way to jump right to matching the next unmatched file in the list (if there is one). Rather than going back out to the list and having to click the "match to scene" button manually. Then you could just blaze through a big list of unmatched files, one after the other, with just a single click each time.

Thanks for all your hard work on this project, it has come a long way since the first alpha. 😄

**Comment by undercutvibes** [comment]
Here's a related request from the feedback page:

> When manually matching scenes, it would be nice to apply the match and have the modal move on to the next file. I've got 600 scenes that aren't matched and it's taking a lot longer to go through them because I need to scroll down to the next file I can match (missing networks, non-VR files in the files list, etc.).
> 
> Having a < and > button in that modal loading the next/previous file for matching would be extremely handy.

**Comment by jrebey** [comment]
LOL, that's my feedback. I'm planning on implementing that soon(ish)
