### ISSUE TITLE
Manual Scene Entry

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#148]
If someone has files from a site without a scraper, it would be nice to have a way to manually provide a URL for the cover image, the scene title, and other basic info. It wouldn't need to be as robust as what a good scraper can do. Maybe tags and performers, just the basics.

This, combined with the enhancements in #141 would allow people to "up-convert" from manual to scraped when/if a scraper is added for the site.

**Comment by seducingbits** [comment]
Seconded this. Just tried the tool and at first glance it looks pretty great but from my 25 scenes only 3 could be matched since the rest are selfmade videos or by smaller productions and not big studio productions.

Putting the images and metadata next to the video file could also work. Would a filenaming convention though.

**Comment by theRealKLH** [comment]
@vpfruitly cleaning "dead" issues. `it's in there.`
