### ISSUE TITLE
Support for DeoVR's "WebVR Hub" feature

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#155]
DeoVR support is really nice! Let's take it a step further and support WebVR!

https://deovr.com/doc/webvr/type/hub

You can see this in action at:

http://www . sexlikereal . com/hub

**Comment by Kaylakaze** [comment]
This shouldn't take more than an hour to implement for someone familiar with the code. Come on people. (I'd do it myself but, I'm not familiar with the code or Go).

**Comment by cld9x** [comment]
@Kaylakaze making such assumptions and expressing them that way won't speed up anything

I am personally not interested in adding (and supporting!) a third method of accessing the library, unless someone picks up the initial effort.

**Comment by Kaylakaze** [comment]
@cld9x Had the request been anything but ignored for over 6 months, I wouldn't have said anything.

**Comment by Kaylakaze** [comment]
So, I actually did some work on this idea and it turns out the DeoVR Hub is NOT what SLR uses. What SLR uses seems to be undocumented and DeoVR has said they have no plans to share any information on it. The WebVR is actually a web-menu using a web-based player. If you load a hub site on DeoVR, it just loads in the browser (and the browser doesn't seem to be able to handle it properly).

**Comment by goldstar1x** [comment]
I'm not sure if this is new or old info but it looks like there's now some documentation on Web Hub from DeoVR's documentation:

https://deovr.com/doc/webvr/type/hub

**Comment by yoshnopa** [comment]
Before anyone tries too hard on this, the hub is currently not supported by the DeoVR App, which seems to be the main reason to implement it in the first place:
https://forum.deovr.com/d/104-deo-webvr-hub-example-help
Although I too would love to have a hub in XBVR, I think it would be of no use right now until DeoVR has updated their app.

**Comment by theRealKLH** [comment]
@yoshnopa you DO realize no one was thinking about working on this? (I COULD be wrong but...) 

This was asked for Oct 2019 AND the owner of XBVR gave his stance on it (not gonna happen by him) AND the last comment here was from Dec 2020 pointing to documentation that has NOT been updated or supported since it was posted.. you yourself supplied link to the DeoVR forum posting where everyone is being "ignored" by DeoVR support on the subject.

**Comment by yoshnopa** [comment]
There is probably no one working on this now, but theres always the chance someone is thinking about adding it (as its an open issue) as well as there may be people awaiting this feature. 
For those I wanted to provide additional context, namely the according DeoVR thread that asks for the prerequisites of this feature.

**Comment by theRealKLH** [comment]
There is no documented use of this feature beyond DeoVR's extremely basic example that they aren't even supporting.
