### ISSUE TITLE
TmwVRnet Scraper requires members link

### ISSUE THREAD

**Issue by pops64** [xbapps/xbvr#1558]
Like other sites that have a members links. tmwVRnet requires a members link.

Scraped link is https://tmwvrnet.com/trailers/{scene_name_here}.html 
Members link is https://members.tmwvrnet.com/scenes/{scene_name_here}.html

Thanks for the greats scrapers

**Comment by toshski** [comment]
I just signed up to teenmegaworld and this doesn't look correct.  
If I go to https://members.tmwvrnet.com/ I get redirected to https://members.teenmegaworld.net/ Same if I try to go a scene e.g. https://members.tmwvrnet.com/scenes/How-do-you-make-a-cheater-behave.html also redirects to https://members.teenmegaworld.net/  i.e. the homepage rather than a scene.  Maybe it depends on where you sign up to.

It also looks like your links would go to an images page for the scene, to go video/download page, it should go to ..._vids.html

Can you confirm the link [https://members.tmwvrnet.com/scenes/{scene_name_here}.html](https://members.tmwvrnet.com/scenes/%7Bscene_name_here%7D.html) would not work for me, for me it would have to be [https://members.teenmegaworld.net/scenes/{scene_name_here}_vids.html](https://members.teenmegaworld.net/scenes/%7Bscene_name_here%7D_vids.html)

**Comment by pops64** [comment]
Yes, I missed the _vids.html part. I haven't gotten any redirects to teenmegaworld but I did sign up through TMW VR not through their 2D site
