### ISSUE TITLE
SLR Images are getting 403 error prior to ~4/2020

### ISSUE THREAD

**Issue by pops64** [xbapps/xbvr#1702]
It seems that SLR images being pulled using this format 
`https://cdn-vr.sexlikereal.com/images/13866/85406_desktop.jpg`
 
creates a 403 error for just the cover scene. When requesting an image in this format 
`https://cdn-vr.sexlikereal.com/images/13866/vr-porn-Sex-In-Public-on-the-Balcony-cover-app.webp`

It pulls that format just fine. I am not sure how XBVR is converting the above format to the one it is using. I found the above by inspecting the webpage and looking for the XBVR formatted link and I couldn't find it. It only happens to the cover scene the rest of the gallery images are just fine. I am not sure if SLR has a bug or what. This also may only effect certain studios. Right now it is just the perVRet family of studios on SLR and VRSolos also on SLR, that I have noticed. The above examples come from https://www.sexlikereal.com/scenes/sex-in-public-on-the-balcony-13866

**Comment by theRealKLH** [comment]
going to say you may need to force update your scenes? I have that scene and my image is
[https://cdn-vr.sexlikereal.com/images/13866/vr-porn-Sex-In-Public-on-the-Balcony-cover-app.jpg](url)

notice `.jpg` instead of `.webp`. Also for me that scene is "set for an update", but not updating. 

This scene is from "Lenina Crowne" which was pulled from the built-in list of scrapers. so I'm going to say that is why you aren't updating. You would need to create custom site.

**Comment by pops64** [comment]
My example was freshly pulled from version 24 it effects the underlying SLR scraper for at least a few studios. They made a change to it in #1616

**Comment by theRealKLH** [comment]
I just scraped VRSolos...
![image](https://github.com/xbapps/xbvr/assets/65736720/c4dcba63-4ca9-4f9d-b9b3-7fb00f2cd3af)
What's the problem again?

**Comment by vt-idiot** [comment]
@theRealKLH your scrape of that scene predates the change to how SLR images are scraped. the slug is still in the URL.

the issue occurs because those perVRt scenes and the LC one have comically small cover images. you can see the artifacts/upscaling in the URL that has the scene slug in it. there is no `_desktop` image for them, but there is an `https://cdn-vr.sexlikereal.com/images/13866/85406_app.jpg`

@pops64 it is not all scenes prior to 04/2020, or even a significant amount of them. I have plenty of scenes from before then that I rescraped before making that change, and didn't notice the glitch. it needs an extra catch for those access denied errors to switch to the `_app` link

**Comment by pops64** [comment]
Yes. So far the studios that are effected that I have noticed are. perVRet, Lenina Crowne, Babykxtten, VReXtasy and maybe Sins Tho this is hard to tell as I only manually import Sins when the parent site has hidden some of there scenes behind a paywall and I usually pull the SLR site over the VRP site, I have both set for alternates to Sins 

Here is a picture from VReXtasy which is a custom made 2 days ago. The only built in scrapers I have noticed are perVRet and VRSolos. It seems this change in naming convention starts around 2/2020 to 4/2020 I have some scenes in February that pull the cover and I have some scenes that don't pull the cover until late march.
![tempsnip](https://github.com/xbapps/xbvr/assets/10678220/0599cc93-95e3-4199-9ba3-1a79debd2bb3)

But yes an error detection switch would be nice. The problem is perVRet doesn't have a naming standard so when matching their scenes to alts your have to do it by cover scene image which breaks around 4/2020 because of this bug.

**Comment by theRealKLH** [comment]
learn son

> @theRealKLH your scrape of that scene predates the change to how SLR images are scraped. the slug is still in the URL.
> 
> the issue occurs because those perVRt scenes and the LC one have comically small cover images. you can see the artifacts/upscaling in the URL that has the scene slug in it. there is no `_desktop` image for them, but there is an `https://cdn-vr.sexlikereal.com/images/13866/85406_app.jpg`

ILSNED!

**Comment by vt-idiot** [comment]
I just tried something and it worked on a full scrape of VRSolos and that LeninaCrowne scene, 0 missing covers. Old scenes get the cover for ants, newer ones with the proper cover get the one they would've anyways.
