### ISSUE TITLE
Database: Thousands of tags with same name and count 0 in table tags

### ISSUE THREAD

**Issue by Samsonite121** [xbapps/xbvr#1707]
I observed now that in the database in the table tags there are for common tags (like blonde, brunette, big tits usw.) thousands of entries for the same name of tag with count 0. I've already seen numbers like about 100000.
Seems like after scraping and counting and consolidating the tags additional not used tags with count 0 are not cleared from the database.
That's annoying because if you use such tags in filtered searches or saved lists as excluded tags it can extremly raise the search time.
I've one example in DeoVR that the display of the scenes raised in time from 7s to s.th. about 20s only why I added one of the tags in question to some list as excluded tag.

**Comment by theRealKLH** [comment]
In my DB I see multiple "cowgirl" with a count of 0. But there are 11737 scenes with that tag. 
![image](https://github.com/xbapps/xbvr/assets/65736720/26ced86d-0557-41a5-9628-b24ae19b0a5a)
If I delete it (because of count = 0), how would I search for "cowgirl"? 

You should probably be looking at `scene_tags` table instead of `tags` table. Example.. There are 2981 "cowgirl" entries in my `tags` table. 2980 of them have a count of 0. Here is snippet..
![image](https://github.com/xbapps/xbvr/assets/65736720/4402006f-6091-432d-805e-63ea5617b886)
So only the first entry has a number (11741 scenes). "cowgirl" is tag # 5 in my DB. No clue what the other 2980 entries are for (not trying to spelunk this one). However if I go to the `scene_tags` table, there are 14448 entries (each a different scene) pointing to tag # 5 (cowgirl). Snippit below (and before you ask I don't know why I have 3 different totals-grin)...
![image](https://github.com/xbapps/xbvr/assets/65736720/8b651df5-494f-4d9e-ac6f-4afc81c1a681)
