### ISSUE TITLE
Support for SLR

### ISSUE THREAD

**Issue by dakonga** [xbapps/xbvr#249]
Actually none of my SLR (sexlikereal.com) content get's scraped, because filenames of SLR differs comparing original studio filnames. Or is there a way to make these filenames comparable?

**Comment by cld9x** [comment]
Which studio we are talking about?

**Comment by dakonga** [comment]
They have files from nearly all known vr studios. But Filenaming is different.

**Comment by NickCh11** [comment]
> Actually none of my SLR (sexlikereal.com) content get's scraped, because filenames of SLR differs comparing original studio filnames. Or is there a way to make these filenames comparable?
Agree cant find 95% of my files

**Comment by Aerowen** [comment]
I think the way how filenames are matched is the wrong approach. All known filename variations of a scene are currently added as an array to the database, in some cases that's easily 10+ variants thanks to all the different resolutions. And some scrapers don't add any filenames at all. With almost 7000 scenes in a database it seems very inefficient.

Another problem is studios can change their naming scheme and with sites like SLR and VRPorn they have their own naming scheme. And I'm sure many people don't even keep the filename as downloaded, I sure don't. I rename everything to the same format of `Studio.releasedate.title.modelnames.H265/H264.resolution.180/360.3dh/3dv.mp4` so I'm sure for me nothing would match (I'm only using it as searchable database right now).

I think the filename matching should use regular expressions instead. Then you could have only a couple of regex solutions per studio and filename variants wouldn't have to be stored at all. It wouldn't matter what resolution a scene is in as you would only only capture important parts like studio, releasedate, title, cast and do matching based on that even if a sceneID is missing.

Probably even better if it would use named captures, so people could add their own regex. For example with my naming scheme, I could add my own regex as something like this: https://regex101.com/r/t29ayT/2

Even if regex turns out not the way to go, I think filename matching should be done by studio file naming format, not by exact scene filename as they were downloaded.

**Comment by cld9x** [comment]
Initial support for SLR landed in v0.3.0-beta.13

**Comment by bgy78uhn** [comment]
> 
i'm searching for a way to auto-rename/bulk-rename my files.
is there a way to rename the file to the folder name it is located in?
or is there a tool that not only matches my files to a database but also renames them?

**Comment by bgy78uhn** [comment]
>I rename everything to the same format of `Studio.releasedate.title-modelnames.H265/H264.resolution.180/360.3dh/3dv.mp4` so I'm sure for me nothing would match (I'm only using it as searchable database right now).
> 

i'm searching for a way to auto-rename/bulk-rename my files.
is there a way to rename the file to the folder name it is located in?
or is there a tool that not only matches my files to a database but also renames them?
