### ISSUE TITLE
Scrape URL for site with existing scraper

### ISSUE THREAD

**Issue by anon-xbvr** [xbapps/xbvr#306]
Related to #148, but in this case, I have files for a site with a scraper, but the scene page is not reached by the default scraper.

For example, https://vrconk.com/virtualreality/scene/id/8-take-me-baby is not indexed via the 'Movies' link on the main vrconk.com page.

Possible implementation suggestions would be to add an additional option to the Options -> Scrapers -> Site -> triple dot menu for "Scrape scene URL" which would provide a popup for the user to paste a URL.  The URL could then be passed to the sceneCollector.OnHTML to scrape that individual page.

**Comment by Aerowen** [comment]
Interesting, that's a 2017 scene and the earliest listed on the movies pages start in 2018, perhaps they've chosen to hide the earlier scenes. But I see the model of that scene is still listed on the pornstars index so maybe we can change it so it also scrapes by models index. A couple of the other scrapers already do this as well.

**Comment by Aerowen** [comment]
After looking further into this I found the scenes are unlisted in both the scenes and model index so model indexing wouldn't work. But I found the missing ones by the scene id in the urls and added them to be scraped and that works fine. Does mean more code for edge-cases in the scrapers but this is the only way to add them...

I found 19 unlisted early scenes by models 'FantAsia', 'Miss K', and 'Emi'. No idea why they're not listed normally, because they are still listed on SexLikeReal for the VRConk studio. Strange how SLR currently has 85 VRconk scenes listed, while the VRconk site only has 75 publicly listed. But with the 19 unlisted ones I get a total of 94 now in XBVR.

I'll submit this soon-ish with some other scraper fixes. Thanks for reporting this. 👍

**Comment by theRealKLH** [comment]
@bongkatana way to go there Mr. necromancer! heh.. couldn't you have glommed onto one of the more recent "manual scraper" issues/discord requests? grin

Viable work-arounds... https://github.com/Tweeticoats/tpdb2xbvr or https://github.com/make-it-fun/GUI-for-tpdb2xbvr

**Comment by theRealKLH** [comment]
heh. YW!
