### ISSUE TITLE
Suggestion for Better File Matching

### ISSUE THREAD

**Issue by Deflated-Criossant** [xbapps/xbvr#342]
ignore file extension and `* 180 180x180 3dh LR`

Compare the score before and after

Default 
![default](https://user-images.githubusercontent.com/16240121/89759313-7c9adf80-db07-11ea-980a-a73d01da1584.jpg)

After removing `oculus 180 180x180 3dh LR mkv`
![After](https://user-images.githubusercontent.com/16240121/89759335-8886a180-db07-11ea-8566-8710836d2c17.jpg)

Q : What is the score needed for the file to be auto-matched?

**Comment by vpfruitly** [comment]
I have a huge stack of regexes that clean up the filename, just haven't made a PR for it yet.

**Comment by SpedNSFW** [comment]
This won't work in all instances though. I've noticed scenes where, I've typed in the format of `studio title`, that the scene I won't still don't be the first one. It'll be 2nd or sometimes third.

Here's an example of this happening.

![example](https://i.imgur.com/w5epN5t.png)

The only automatching occurs when a filename matches what is set in a scraper, because as you can see, you cannot guarantee it will be accurate.

**Comment by vpfruitly** [comment]
Yeah, I think auto matching on anything less than an EXACT filename match is a non-starter. Way too easy for it to get the match wrong, and as of right now, there's still no method to un-match or rematch.

That said, cleaning up the input field by stripping out all the bullshit parts of the filename does result in much, MUCH better "first 5" matches.

**Comment by SpedNSFW** [comment]
Any RegEx pattern that works for all studios is going to be a long one. Probably better to have a RegEx for each different naming pattern since some studios are similar (Badoink, Wankz, VRBangers), and then others are completely different to anything else (VirtualTaboo, Naughty America)

**Comment by vpfruitly** [comment]
I think we're talking about two different things. All my regexes do is clear out the generic junk like 2160 and 180_180x180_3dh_LR so that the fuzzy search is done on only the parts of the filename that actually matter. It has a bigger effect on the quality of results than you'd expect. But yes, it is a long one, though the computational time is trivial, so it's not like it matters.
