### ISSUE TITLE
BadoinkVR scene link not on main scene page

### ISSUE THREAD

**Issue by T120S3** [xbapps/xbvr#523]
BadoinkVR scene link not visible on main scene page.

**Comment by theRealKLH** [comment]
need more information. what scene link?

**Comment by T120S3** [comment]
For BadoinkVR, none of the links show up on the main scene page. Just the date. 
<img width="482" alt="2021-05-24" src="https://user-images.githubusercontent.com/81692988/119367540-0d4e4080-bc80-11eb-9ba8-aaf427551a28.png">

**Comment by theRealKLH** [comment]
I could be wrong, but I'm gonna say this goes back again to you having a corrupted DB...
![image](https://user-images.githubusercontent.com/65736720/119379121-12fe5300-bc8d-11eb-9031-64658ad0c0df.png)

I would suggest temporarily renaming your main.db and try scraping BaDoinkVR...

**Comment by T120S3** [comment]
I will do that. Obviously the issue is that I have a large library and rebuilding it, while it can be done, is painful. 

Any suggestions for repairing, or if not repair and I have to rebuild, keeping it from happening again??

If certain tasks, when combined, like scraping and scanning and/or manual matching can corrupt the DB it might be useful to not allow other tasks to be performed when something else is running? 

This app is amazing in so many ways, and needed. Thanks to all who are creating it.

**Comment by theRealKLH** [comment]
I've gone through several rebuilds, I know the pain of the big libraries. not to mention that a lot of times my system can take upwards of 1 hour to do a scrape adding a measly 20 or so new scenes. one thing that helps is to perform backups every once in awhile to keep the amount of scraping to a minimum after a bad crash or corruption.

I don't have any suggestions regarding DBs. I was going to say do a "forced update", but since you are showing new scenes coming in messed up, it just sounds like... "I don't even know.".

I believe there may have been something added to limit scraping/scanning/manual matching overlap, but not 100 on that. I can say if you aren't manually doing anything, scraping is once per day, scanning is every 2 hours, and everything else is manual.

**Comment by cld9x** [comment]
@T120S3 disable adblocker - badoink's domain is on one of default blocklists for some reason

**Comment by theRealKLH** [comment]
@cld9x that's some crazy mess... which adblocker?

**Comment by T120S3** [comment]
I have adblock plus, and yes, that is the culprit. Thanks for that!
