### ISSUE TITLE
R18 titles with a blank DVD ID cause issues - can't be matched to any files

### ISSUE THREAD

**Issue by vt-idiot** [xbapps/xbvr#611]
CRVR-131 is a good example. It didn't come up in the search bar on R18, but I knew I'd seen it on there before. Searching by the actress/title did let me find it on the site and scrape it: `https://www.r18.com/videos/vod/movies/detail/-/id=h_1155crvr00131/`
It did import, but with two issues, one easily corrected, and one not:
1. the site initially imported as `h_1155crvr00131`
2. the "ID" is blank

It was easy enough to manually change the site to CRVR. There isn't actually a way to edit the ID, and XBVR never shows it in the manual match results, presumably because it has no ID. The extra "CRVR-131" tag was an attempt to force it to show up before I noticed there was no ID.

![image](https://user-images.githubusercontent.com/81622808/142079682-1f2714b7-78d3-4fc2-a842-d573560d5709.png)

speaking of JAV, there has to be a better way to do this. The R18 "scraper" doesn't actually work with DVD IDs from what I can tell, and it does nothing unless I give it the full URL.

I tried to "Export Content Bundle" so I could maybe take a look at how entries are structured and try and write JSON bundles for titles that aren't on R18 but are otherwise available, either directly from Fanza in Japan or on Afesta, but I think that must've started the Preview generator or something, because it's been doing that for hours now. The ability to make manual entries directly from the interface would be an easy solution, for now at least #442 

The rest of this quickly became a scraper request, so I'll go write that over there.

**Comment by theRealKLH** [comment]
Export Content Bundle won't give you any R18 content due to the way the export function works. It is NOT exporting your database, but exporting the result of a scrape task (which does not scrape R18).

IF you are looking for a JAV site that's hosted on SLR, then that's a "please add xxxx to the SLR scraper". I doubt there will ever be a full R18 scraper added to xbvr (at least not by the xbvr creator) other than what you already get.

For the "manual" stuff, try...

[https://github.com/Tweeticoats/tpdb2xbvr](url) or [https://github.com/make-it-fun/GUI-for-tpdb2xbvr](url)
