### ISSUE TITLE
some videos like fisheye aren't playing correctly in deovr app after matching

### ISSUE THREAD

**Issue by andreaaraya01** [xbapps/xbvr#726]
I have see that if you match a file with a scene, later in deovr app the scene is not played as the filename says, I mean if file has _mkx200 for fisheye and in deovr app you will see the streching in top and bottom area of video, if you don't match the video and later you watch that video in "unmatched" list, you will see the video correctly without the strech produced by bad fisheye render.

I don't know if this is a problem with xbvr or deovr app, if xbvr doesn't has the problem please close this issue.

**Comment by vt-idiot** [comment]
It's an issue with XBVR. I haven't figured out where XBVR stores its DeoVR specific info even after poring through the entire .db file, but if you match _any_ video to a particular scene, that scene will forever have _that_ particular projection. e.g. if I have a file that doesn't have "mkx200" in the filename and I manually match it to a scene, it will now render LR/180, even if I unmatch that file, and then download an mkx200 file that has _mkx200 in the filename.

XBVR "decides" what projection a _file_ is when it scans it. If you rename a file and re-scan, XBVR will re-detect its projection. XBVR decides what projection a _scene_ is when the *first* file match is made to that scene. There is *no way* to change this.

The only fix I've found involves manually editing the .db file. Easy enough to fix for JAV, I can just copy the entry and add "-T" or Takumi or whatever to the scene ID. JAV or otherwise, you have to copy the entry and give it a different scene ID.

**Comment by theRealKLH** [comment]
I had to pull #718. It was working in all my tests so I submitted it. Just went back to it preparing for the "great merge of 05/22" and it is no longer working. This is not a "XBVR" issue. I don't know of ANY SLR scenes (what DeoVR was "created" for) that feature multiple projections. There is no way to dynamically update the information because it is sent as a scene list and DeoVR is using "scene" details not "file" details. "Unmatched" are sent as a list as well, but each video is sent as it's own "scene", which is why those don't have the same problem. It all comes down to DeoVR isn't expecting there to be different projections, and they have removed any way for us (DeoVR users) to change it manually for EVERY "scene" we might play. Whether we change it for the good or worse. They know better than you about what you want/need.

**Comment by theRealKLH** [comment]
Sorry, just seeing this after all this time...

Just a couple of points to expand on your responses...

> That also explains why manually editing the database to copy the scene and give it a different scene_id will fix any videos

 I believe any change to the filename would also fix. But who wants to do that? (potential break auto-match) GRIN.  However, if you happen to add a different version of the video again in the future with the old name, it would still have the original (possibly wrong) projection. Hence the need to delete the DeoVR cache (**to clear quest native version data means uninstall/install DeoVR in case that wasn't known**).

> On a somewhat related note, and at the risk of sounding like a shill, if you're having projection issues in general, check out HereSphere.

shut up you SHILL!!  Heh.. seriously, HereSphere is a great addition to the VR video player category (now me risking the shill helmet-heh). **PRO** If you are on quest/quest2 hardware, there is the native player.. No need for Steam or PC. Unfortunately the **CON** is if you've already purchased the PC version, it would be a double dip. 

> It will grab Favorites/Ratings from XBVR but it doesn't seem like it sends them back if you set them within HereSphere

This is actually a SLR only feature. The heart is actually tied to "favorites" on the SLR website, NOT YOUR favorite scenes in your library. DeoVR works the same. If you aren't "logged in" and on SLR website, you will get an error.

> I'm not entirely sure the Remote Control feature works in DeoVR anyways, but at this point, I'm willing to bet that is their fault, not XBVR's.

I believe this does work as it should, it just may be a bit confusing on how/when we (as users) are actually supposed to enable / disable the feature within XBVR.

> https://github.com/xbapps/xbvr/issues/623 might be interested in this as well, especially considering that it isn't really something XBVR can implement beyond pre-saving playlists for DeoVR to look at

YUP.. this is a limitation of XBVR due to DeoVR reneging (someone feel free to correct me if I'm misspeaking) on releasing their API that SLR is using. Only the very basic necessities have been given... which is why #623... #708... #726... etc...

**Comment by meihaco** [comment]
Convert SLR fisheye (200° or 190°) to normal 180° video with FFmpeg:

```bash
ffmpeg -i input.mp4 -filter:v "v360=input=fisheye:ih_fov=200:iv_fov=200:output=hequirect:in_stereo=sbs:out_stereo=sbs" -map 0 -c:a copy -c:s copy -c:v libx264 -preset slow -pix_fmt yuv420p output.mp4
```

- Replace `input.mp4` with your file name.
- Change `ih_fov=200` and `iv_fov=200` to `190` if your original is 190°.
- `output.mp4` will be a standard 180° equirectangular video, playable anywhere.

Done! After conversion, you don't need the SLR app.
