### ISSUE TITLE
Naughty America Scraper grabbing only up to 2018. Missing everything 2018 and beyond

### ISSUE THREAD

**Issue by ostrichsauce** [xbapps/xbvr#944]
I've been having to manually import scenes from Naughty America VR as the scraper is only grabbing 2015-2018. Is this a known issue and if so how can I resolve it? 

Thanks.

**Comment by toshski** [comment]
I've created a clean xbvr environment and scrapped NAVR.  I only got approx 250 scenes.  Browsing to their site I had a Human Verification check, so I solved the puzzle and browsed a couple of scenes.  I retried scrapping and got nothing, restarted xbvr and after about 5-10 minutes it then re-scrapped another 230 scenes.  So I did this process a few times to get the lot.  Not exactly sure why xbvr would not rescrap straight away after solving the Human verification puzzle, it does do some caching so maybe that's why I had to restart and wait a bit.

Some other tricks that may help are 

1. browse around their site while scrapping, this may popup the HV check which you can then solve and maybe not miss as many on the scrap run.  

1. If you use a VPN service, reconnecting via a different server/country can help as well.

You just have to work with, as we can't get around it with the scrapper

**Comment by theRealKLH** [comment]
@ostrichsauce cleaning up "dead" issues. if still an issue, reopen with more information. I think this is/was due to captcha?
